sudo: required
services:
  - docker

before_install:
  - docker build -t sumanth9571/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sumanth9571/react-test npm test -- --coverage
# script:
#   - docker run -e CI=true sumanth9571/react-test npm test

after_success:
  - docker build -t sumanth9571/multi-client ./client
  - docker build -t sumanth9571/multi-nginx ./nginx
  - docker build -t sumanth9571/multi-server ./server
  - docker build -t sumanth9571/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sumanth9571/multi-client
  - docker push sumanth9571/multi-nginx
  - docker push sumanth9571/multi-server
  - docker push sumanth9571/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-152736127367"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"